// Code generated by MockGen. DO NOT EDIT.
// Source: helper.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
)

// MockValidatorInterface is a mock of ValidatorInterface interface.
type MockValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorInterfaceMockRecorder
}

// MockValidatorInterfaceMockRecorder is the mock recorder for MockValidatorInterface.
type MockValidatorInterfaceMockRecorder struct {
	mock *MockValidatorInterface
}

// NewMockValidatorInterface creates a new mock instance.
func NewMockValidatorInterface(ctrl *gomock.Controller) *MockValidatorInterface {
	mock := &MockValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidatorInterface) EXPECT() *MockValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateUnknownParams mocks base method.
func (m *MockValidatorInterface) ValidateUnknownParams(reqBody interface{}, ctx *gin.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUnknownParams", reqBody, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUnknownParams indicates an expected call of ValidateUnknownParams.
func (mr *MockValidatorInterfaceMockRecorder) ValidateUnknownParams(reqBody, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUnknownParams", reflect.TypeOf((*MockValidatorInterface)(nil).ValidateUnknownParams), reqBody, ctx)
}
